### PR TITLE
fix: query params 

### LINKED ISSUE #29: Word Counts & Separators Stuck on Defaults
PP stopped honoring query params somewhere around early June. It always shows 4 words and hyphens, no matter if you change the query params or change the toggles on the website itself.

eg: https://passplum.com/?w=7&sep=.

### PR DESCRIPTION
**Pull request by maxbeatty**
fixes #29 

good timing https://zeit.co/blog/now-node-helpers

### CODE REVIEW

File: src/routes/index.js [hunk 1]
```diff
@@ -12,23 +8,21 @@ const MAX_LEN = 7;
 
 const v = new Vault();
 
-module.exports = micro(async (req, res) => {
+module.exports = async (req /*: $FlowFixMe */, res /*: $FlowFixMe */) => {
   try {
     let LENGTH /*: number */ = 4;
     let SEPARATOR = "-";
 
-    const { query } = parse(req.url);
```
Comment (maxbeatty) [inline src/routes/index.js]: the smaller fix...

```diff
- const { query } = parse(req.url);
+ const { query } = parse(req.url, true);
```

File: src/routes/index.js [hunk 2]
```diff
@@ -12,23 +8,21 @@ const MAX_LEN = 7;
...
-
-    if (query) {
-      if (query.w) {
-        LENGTH = Number(query.w);
+    if (req.query) {
```
Comment (lucleray) [inline src/routes/index.js]: Sorry to be late here, but just a small tip : `req.query` is `{}` by default so you don't need to check that `req.query` is not undefined 🙂

(cool to see that you're using helpers by the way 🙏)
